version: '2'
services:
  zookeeper:
    image: zookeeper:3.8.0
    ports:
      - 12181:2181
      - 12182:2182
    environment:
      - SERVER_ID=1
      - SERVER_COUNT=1
      - SERVER_NAME=zookeeper
      - QUORUM_AUTH_ENABLED=false
      - ENABLE_SSL=false
      - ENABLE_2WAY_SSL=false
      - ALLOW_NONENCRYPTED_ACCESS=false
  zookeeper-backup-daemon:
    image:  ghcr.io/netcracker/qubership-zookeeper-backup-daemon:latest
    ports:
      - 8080:8080
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_HOST=zookeeper
      - ZOOKEEPER_PORT=2181
      - BACKUP_SCHEDULE=0 * * * *
      - EVICTION_POLICY=1h/1h
      - IPV6=false
      - ZOOKEEPER_BACKUP_DAEMON_DEBUG=DEBUG
      - LOG_LEVEL=DEBUG
      - ZOOKEEPER_ENABLE_SSL=false